package filesystem_test

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/ToledoVitor/GoContext/internal/ingest"
	"github.com/ToledoVitor/GoContext/internal/ingest/filesystem"
	"github.com/ToledoVitor/GoContext/internal/source"
)

func TestScannerIncludesSupportedFilesWithRepositoryRelativeReferences(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "app.py", "def main():\n    return 1\n")
	writeFile(t, root, "src/app.ts", "export function main() {\n  return 1\n}\n")
	writeFile(t, root, "src/view.tsx", "export const View = () => <div />\n")

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if result.PolicyVersion != ingest.ScanPolicyVersion {
		t.Errorf("PolicyVersion = %q, want %q", result.PolicyVersion, ingest.ScanPolicyVersion)
	}
	if result.Report.EligibleFiles != 3 || result.Report.IncludedFiles != 3 {
		t.Errorf("file counts = eligible %d, included %d; want 3 and 3", result.Report.EligibleFiles, result.Report.IncludedFiles)
	}
	if result.Report.IncludedByLanguage[source.LanguagePython] != 1 || result.Report.IncludedByLanguage[source.LanguageTypeScript] != 2 {
		t.Errorf("IncludedByLanguage = %#v, want one Python and two TypeScript", result.Report.IncludedByLanguage)
	}

	want := []struct {
		path     string
		language source.Language
		endLine  int
	}{
		{path: "app.py", language: source.LanguagePython, endLine: 2},
		{path: "src/app.ts", language: source.LanguageTypeScript, endLine: 3},
		{path: "src/view.tsx", language: source.LanguageTypeScript, endLine: 1},
	}
	if len(result.Files) != len(want) {
		t.Fatalf("Scan() returned %d files, want %d", len(result.Files), len(want))
	}
	for i, expected := range want {
		if got := result.Files[i].Reference.Path; got != expected.path {
			t.Errorf("files[%d].Reference.Path = %q, want %q", i, got, expected.path)
		}
		if got := result.Files[i].Language; got != expected.language {
			t.Errorf("files[%d].Language = %q, want %q", i, got, expected.language)
		}
		if got := result.Files[i].Reference.StartLine; got != 1 {
			t.Errorf("files[%d].Reference.StartLine = %d, want 1", i, got)
		}
		if got := result.Files[i].Reference.EndLine; got != expected.endLine {
			t.Errorf("files[%d].Reference.EndLine = %d, want %d", i, got, expected.endLine)
		}
		if !result.Files[i].Reference.Valid() {
			t.Errorf("files[%d].Reference = %#v, want valid reference", i, result.Files[i].Reference)
		}
	}
}

func TestScannerClassifiesUnsafeContentAndReportsOnlyAggregates(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "keep.py", "print('safe source')\n")
	writeFileBytes(t, root, "invalid.py", []byte("print('prefix')\n\xff"))
	writeFile(t, root, "generated.py", "# Code generated by fixture. DO NOT EDIT.\nVALUE = 1\n")
	writeFile(t, root, "identity.py", "KEY = '''-----BEGIN PRIVATE KEY-----\nprivate-canary\n'''\n")
	writeFile(t, root, "cloud.py", "AWS_ACCESS_KEY_ID = 'AKIAABCDEFGHIJKLMNOP'\n")
	writeFile(t, root, "config.ts", "export const password = 'literal-canary'\n")
	writeFileBytes(t, root, "binary.py", []byte{'p', 'r', 'i', 'n', 't', 0, 'x'})
	writeFileBytes(t, root, "large.ts", bytes.Repeat([]byte{'x'}, int(filesystem.DefaultMaxFileSize)+1))
	writeFile(t, root, "README.md", "unsupported-canary\n")
	makeSpecialFile(t, filepath.Join(root, "pipe.py"))

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if got := filePaths(result.Files); len(got) != 1 || got[0] != "keep.py" {
		t.Fatalf("Scan() paths = %v, want [keep.py]", got)
	}
	wantExcluded := map[ingest.ExclusionReason]int{
		ingest.ExclusionInvalidUTF8:          1,
		ingest.ExclusionGenerated:            1,
		ingest.ExclusionSecret:               3,
		ingest.ExclusionBinary:               1,
		ingest.ExclusionTooLarge:             1,
		ingest.ExclusionNonRegular:           1,
		ingest.ExclusionUnsupportedExtension: 1,
	}
	for reason, want := range wantExcluded {
		if got := result.Report.Excluded[reason]; got != want {
			t.Errorf("excluded[%q] = %d, want %d", reason, got, want)
		}
	}
	if result.Report.IncludedFiles != 1 || result.Report.IncludedByLanguage[source.LanguagePython] != 1 {
		t.Errorf("included report = %#v, want one Python file", result.Report)
	}
	if got := result.Report.UnsupportedByExtension[".md"]; got != 1 {
		t.Errorf("unsupported .md count = %d, want 1", got)
	}

	payload, err := json.Marshal(result.Report)
	if err != nil {
		t.Fatalf("Marshal(report) error = %v", err)
	}
	for _, sensitive := range []string{"invalid.py", "private-canary", "literal-canary", "unsupported-canary", "AKIAABCDEFGHIJKLMNOP"} {
		if bytes.Contains(payload, []byte(sensitive)) {
			t.Errorf("report = %s, must not contain %q", payload, sensitive)
		}
	}
}

func TestScannerExcludesLiteralSecretsAfterTypeAnnotations(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "keep.py", "message: str = 'public'\n")
	writeFile(t, root, "typed.py", "password: str = \"python-prod-canary\"\n")
	writeFile(t, root, "typed.ts", "const password: string = \"typescript-prod-canary\"\n")

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if got := filePaths(result.Files); len(got) != 1 || got[0] != "keep.py" {
		t.Fatalf("Scan() paths = %v, want [keep.py]", got)
	}
	if got := result.Report.Excluded[ingest.ExclusionSecret]; got != 2 {
		t.Fatalf("secret exclusions = %d, want 2", got)
	}
}

func TestScannerFindsLiteralSecretsInLaterSameLineStatementsWithoutFlaggingOperators(t *testing.T) {
	tests := []struct {
		name          string
		extension     string
		secretSource  string
		allowedSource string
	}{
		{
			name:          "python",
			extension:     ".py",
			secretSource:  "safe = \"x\"; password: str = \"python-prod-canary\"\n",
			allowedSource: "password = lookup(); safe = \"x\"; matches = password == \"prod\"\n",
		},
		{
			name:          "typescript",
			extension:     ".ts",
			secretSource:  "const safe = \"x\"; const password: string = \"typescript-prod-canary\"\n",
			allowedSource: "const password = lookup(); const safe = \"x\"; const matches = password === \"prod\"; const render = () => \"prod\";\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			allowedPath := "allowed" + tt.extension
			writeFile(t, root, allowedPath, tt.allowedSource)
			writeFile(t, root, "unsafe"+tt.extension, tt.secretSource)

			result, err := filesystem.NewScanner().Scan(context.Background(), root)
			if err != nil {
				t.Fatalf("Scan() error = %v", err)
			}
			if got := filePaths(result.Files); len(got) != 1 || got[0] != allowedPath {
				t.Fatalf("Scan() paths = %v, want [%s]", got, allowedPath)
			}
			if got := result.Report.Excluded[ingest.ExclusionSecret]; got != 1 {
				t.Fatalf("secret exclusions = %d, want 1", got)
			}
		})
	}
}

func TestScanReportBucketsUnrecognizedExtensionsWithoutLeakingNameFragment(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "keep.py", "print('safe')\n")
	writeFile(t, root, "README.md", "documentation\n")
	writeFile(t, root, "notes.customer-canary", "private naming convention\n")

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if got := result.Report.UnsupportedByExtension[".md"]; got != 1 {
		t.Errorf("unsupported .md count = %d, want 1", got)
	}
	if got := result.Report.UnsupportedByExtension["<other>"]; got != 1 {
		t.Errorf("unsupported <other> count = %d, want 1", got)
	}
	payload, err := json.Marshal(result.Report)
	if err != nil {
		t.Fatalf("Marshal(report) error = %v", err)
	}
	if bytes.Contains(payload, []byte("customer-canary")) || bytes.Contains(payload, []byte("notes")) {
		t.Fatalf("report = %s, want repository-specific suffix bucketed", payload)
	}
}

func TestScannerPreflightsNestedRepositoriesBeforeAnyChild(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".git/config", "root metadata\n")
	writeFile(t, root, "keep.py", "print('keep')\n")
	writeFile(t, root, "nested-directory/!.py", "print('must not be read')\n")
	writeFile(t, root, "nested-directory/.git/config", "nested metadata\n")
	writeFile(t, root, "nested-gitfile/!.ts", "export const mustNotBeRead = true\n")
	writeFile(t, root, "nested-gitfile/.git", "gitdir: ../metadata\n")

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if got := filePaths(result.Files); len(got) != 1 || got[0] != "keep.py" {
		t.Fatalf("Scan() paths = %v, want [keep.py]", got)
	}
	if got := result.Report.Excluded[ingest.ExclusionNestedRepository]; got != 2 {
		t.Fatalf("nested repository exclusions = %d, want 2", got)
	}
}

func TestScannerExcludesUnsupportedFilesAndIgnoredDirectories(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "keep.py", "print('keep')\n")
	writeFile(t, root, "README.md", "ignore\n")

	for _, directory := range []string{
		".git", ".gocontext", ".next", ".venv", "__pycache__",
		"build", "coverage", "dist", "node_modules", "vendor", "venv",
	} {
		writeFile(t, root, filepath.Join(directory, "ignored.ts"), "export const ignored = true\n")
	}

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if len(result.Files) != 1 || result.Files[0].Reference.Path != "keep.py" {
		t.Fatalf("Scan() paths = %v, want [keep.py]", filePaths(result.Files))
	}
}

func TestScannerExcludesBinaryAndOversizedFiles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "keep.py", "print('keep')\n")
	writeFileBytes(t, root, "binary.py", []byte{'p', 'r', 'i', 'n', 't', 0, 'x'})
	writeFileBytes(t, root, "large.ts", bytes.Repeat([]byte{'x'}, int(filesystem.DefaultMaxFileSize)+1))

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if len(result.Files) != 1 || result.Files[0].Reference.Path != "keep.py" {
		t.Fatalf("Scan() paths = %v, want [keep.py]", filePaths(result.Files))
	}
}

func TestScannerDoesNotFollowSymlinksOutsideRoot(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	writeFile(t, outside, "secret.py", "SECRET = true\n")
	if err := os.Symlink(filepath.Join(outside, "secret.py"), filepath.Join(root, "linked.py")); err != nil {
		t.Skipf("symlink unavailable: %v", err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "linked-dir")); err != nil {
		t.Skipf("directory symlink unavailable: %v", err)
	}

	result, err := filesystem.NewScanner().Scan(context.Background(), root)
	if err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	if len(result.Files) != 0 {
		t.Fatalf("Scan() paths = %v, want no files", filePaths(result.Files))
	}
}

func TestScannerRejectsInvalidRootAndCancellation(t *testing.T) {
	scanner := filesystem.NewScanner()
	if _, err := scanner.Scan(context.Background(), filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("Scan() missing root error = nil, want error")
	}

	fileRoot := filepath.Join(t.TempDir(), "file.py")
	if err := os.WriteFile(fileRoot, []byte("print('x')\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
	if _, err := scanner.Scan(context.Background(), fileRoot); err == nil {
		t.Fatal("Scan() file root error = nil, want error")
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := scanner.Scan(ctx, t.TempDir()); err == nil {
		t.Fatal("Scan() canceled context error = nil, want error")
	}
}

func writeFile(t *testing.T, root, relativePath, content string) {
	t.Helper()
	writeFileBytes(t, root, relativePath, []byte(content))
}

func writeFileBytes(t *testing.T, root, relativePath string, content []byte) {
	t.Helper()
	path := filepath.Join(root, relativePath)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("MkdirAll(%q) error = %v", relativePath, err)
	}
	if err := os.WriteFile(path, content, 0o600); err != nil {
		t.Fatalf("WriteFile(%q) error = %v", relativePath, err)
	}
}

func filePaths(files []source.File) []string {
	paths := make([]string, len(files))
	for i := range files {
		paths[i] = files[i].Reference.Path
	}
	return paths
}
